{
    "count":40,
    "data":[
        {
            "itemId":86894,
            "itemName":null,
            "customerId":"ceshi",
            "title":"45",
            "content":"4354",
            "commonWordId":86894,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86888,
            "itemName":null,
            "customerId":"ceshi",
            "title":"地方地方个",
            "content":"电饭锅",
            "commonWordId":86888,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86887,
            "itemName":null,
            "customerId":"ceshi",
            "title":"654",
            "content":"也挺好",
            "commonWordId":86887,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86886,
            "itemName":null,
            "customerId":"ceshi",
            "title":"测试数据车丝数据手动合肥市看风景时客户端付扩所军军军军军军军军军军军军军军军军军军军军军军军军斯柯达军军军军军军军军军军军军军军军军军军军军军军军军军军军看闪电发货水库附近看斯柯达付军军军军军军军军军军军军军军军军军军军军军军军开始地方开始放假看收水电费 到货福克斯房价开始发生水电费sdf",
            "content":"测试数据车丝数据手动合肥市看风景时客户端付扩所军军军军军军军军军军军军军军军军军军军军军军军军斯柯达军军军军军军军军军军军军军军军军军军军军军军军军军军军看闪电发货水库附近看斯柯达付军军军军军军军军军军军军军军军军军军军军军军军开始地方开始放假看收水电费 到货福克斯房价开始发生水电费sdf",
            "commonWordId":86886,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86884,
            "itemName":null,
            "customerId":"ceshi",
            "title":"12",
            "content":"023",
            "commonWordId":86884,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86822,
            "itemName":null,
            "customerId":"ceshi",
            "title":"测试11111111",
            "content":"222",
            "commonWordId":86861,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86622,
            "itemName":null,
            "customerId":"ceshi",
            "title":"套电234",
            "content":"您有目前的照片吗？可以通过微信的方式发送给我，我简单看下情况，给您设计一个合理的方案",
            "commonWordId":86828,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86784,
            "itemName":null,
            "customerId":"ceshi",
            "title":"13",
            "content":"13",
            "commonWordId":86824,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86828,
            "itemName":null,
            "customerId":"ceshi",
            "title":"测试123",
            "content":"123",
            "commonWordId":86822,
            "categoryId":12641,
            "companyId":null
        },
        {
            "itemId":86861,
            "itemName":null,
            "customerId":"ceshi",
            "title":"测试123",
            "content":"123",
            "commonWordId":86784,
            "categoryId":12641,
            "companyId":null
        }
    ],
    "code":"0",
    "msg":"ms"
}