{
    "msg":"ok",
    "code":"0",
    "data":[
        {
            "id":"2754",
            "pid":"2753",
            "categoryId":2754,
            "categoryName":"02",
            "categoryMemo":null,
            "parentId":2753,
            "companyId":1
        },
        {
            "id":"2753",
            "pid":"-1",
            "categoryId":2753,
            "categoryName":"28测试",
            "categoryMemo":"给对方看过后就地方看过对访客感觉发的空格今飞凯达低空飞过京东方科技领导反馈了的李开复卡罗拉打开了法国单联开关低空飞过点开链接大方了氪金大佬",
            "parentId":0,
            "companyId":1
        },
        {
            "id":"2582",
            "pid":"2580",
            "categoryId":2582,
            "categoryName":"22",
            "categoryMemo":"22",
            "parentId":2580,
            "companyId":1
        },
        {
            "id":"2589",
            "pid":"2587",
            "categoryId":2589,
            "categoryName":"11",
            "categoryMemo":"11",
            "parentId":2587,
            "companyId":1
        },
        {
            "id":"2625",
            "pid":"2624",
            "categoryId":2625,
            "categoryName":"312321",
            "categoryMemo":"3213213",
            "parentId":2624,
            "companyId":1
        },
        {
            "id":"2588",
            "pid":"2587",
            "categoryId":2588,
            "categoryName":"11",
            "categoryMemo":"11",
            "parentId":2587,
            "companyId":1
        },
        {
            "id":"2599",
            "pid":"2598",
            "categoryId":2599,
            "categoryName":"2222",
            "categoryMemo":"22222",
            "parentId":2598,
            "companyId":1
        },
        {
            "id":"2592",
            "pid":"2591",
            "categoryId":2592,
            "categoryName":"11",
            "categoryMemo":"11",
            "parentId":2591,
            "companyId":1
        },
        {
            "id":"2604",
            "pid":"2603",
            "categoryId":2604,
            "categoryName":"1",
            "categoryMemo":"1",
            "parentId":2603,
            "companyId":1
        },
        {
            "id":"2602",
            "pid":"2601",
            "categoryId":2602,
            "categoryName":"1",
            "categoryMemo":"1",
            "parentId":2601,
            "companyId":1
        },
        {
            "id":"2623",
            "pid":"2622",
            "categoryId":2623,
            "categoryName":"1",
            "categoryMemo":"1",
            "parentId":2622,
            "companyId":1
        },
        {
            "id":"2607",
            "pid":"2606",
            "categoryId":2607,
            "categoryName":"1",
            "categoryMemo":"1",
            "parentId":2606,
            "companyId":1
        },
        {
            "id":"2630",
            "pid":"2629",
            "categoryId":2630,
            "categoryName":"312321",
            "categoryMemo":"321321",
            "parentId":2629,
            "companyId":1
        },
        {
            "id":"2626",
            "pid":"2624",
            "categoryId":2626,
            "categoryName":"123213",
            "categoryMemo":"213213",
            "parentId":2624,
            "companyId":1
        },
        {
            "id":"2628",
            "pid":"2627",
            "categoryId":2628,
            "categoryName":"21321321",
            "categoryMemo":"312321",
            "parentId":2627,
            "companyId":1
        },
        {
            "id":"2693",
            "pid":"-1",
            "categoryId":2693,
            "categoryName":"测试123",
            "categoryMemo":"123",
            "parentId":0,
            "companyId":1
        },
        {
            "id":"2643",
            "pid":"-1",
            "categoryId":2643,
            "categoryName":"2",
            "categoryMemo":"3",
            "parentId":0,
            "companyId":1
        },
        {
            "id":"2694",
            "pid":"2693",
            "categoryId":2694,
            "categoryName":"测试345",
            "categoryMemo":"3454",
            "parentId":2693,
            "companyId":1
        },
        {
            "id":"2644",
            "pid":"2643",
            "categoryId":2644,
            "categoryName":"1",
            "categoryMemo":"1",
            "parentId":2643,
            "companyId":1
        },
        {
            "id":"2713",
            "pid":"-1",
            "categoryId":2713,
            "categoryName":"测试",
            "categoryMemo":"测试测试测试测试测试",
            "parentId":0,
            "companyId":1
        },
        {
            "id":"2714",
            "pid":"-1",
            "categoryId":2714,
            "categoryName":"测试2",
            "categoryMemo":"测试2测试2测试2测",
            "parentId":0,
            "companyId":1
        },
        {
            "id":"2736",
            "pid":"2735",
            "categoryId":2736,
            "categoryName":"123",
            "categoryMemo":"123",
            "parentId":2735,
            "companyId":1
        },
        {
            "id":"2735",
            "pid":"-1",
            "categoryId":2735,
            "categoryName":"测试123",
            "categoryMemo":"测试123",
            "parentId":0,
            "companyId":1
        }
    ],
    "count":23
}